import { paramCase } from 'src/utils/change-case';

import { _id, _postTitles } from 'src/_mock/assets';

// ----------------------------------------------------------------------

const MOCK_ID = _id[1];

const MOCK_TITLE = _postTitles[2];

const ROOTS = {
  AUTH: '/auth',
  AUTH_DEMO: '/auth-demo',
  DASHBOARD: '/dashboard',
};

// ----------------------------------------------------------------------

export const paths = {
  comingSoon: '/coming-soon',
  maintenance: '/maintenance',
  pricing: '/pricing',
  payment: '/payment',
  about: '/about-us',
  contact: '/contact-us',
  faqs: '/faqs',
  page403: '/error/403',
  page404: '/error/404',
  page500: '/error/500',
  components: '/components',
  docs: 'https://docs.minimals.cc',
  changelog: 'https://docs.minimals.cc/changelog',
  zoneUI: 'https://mui.com/store/items/zone-landing-page/',
  minimalUI: 'https://mui.com/store/items/minimal-dashboard/',
  freeUI: 'https://mui.com/store/items/minimal-dashboard-free/',
  figma:
    'https://www.figma.com/file/hjxMnGUJCjY7pX8lQbS7kn/%5BPreview%5D-Minimal-Web.v5.4.0?type=design&node-id=0-1&mode=design&t=2fxnS70DuiTLGzND-0',
  product: {
    root: `/product`,
    checkout: `/product/checkout`,
    details: (id) => `/product/${id}`,
    demo: {
      details: `/product/${MOCK_ID}`,
    },
  },
  post: {
    root: `/post`,
    details: (title) => `/post/${paramCase(title)}`,
    demo: {
      details: `/post/${paramCase(MOCK_TITLE)}`,
    },
  },
  // AUTH
  auth: {
    amplify: {
      login: `${ROOTS.AUTH}/amplify/login`,
      verify: `${ROOTS.AUTH}/amplify/verify`,
      register: `${ROOTS.AUTH}/amplify/register`,
      newPassword: `${ROOTS.AUTH}/amplify/new-password`,
      forgotPassword: `${ROOTS.AUTH}/amplify/forgot-password`,
    },
    jwt: {
      login: `${ROOTS.AUTH}/jwt/login`,
      register: `${ROOTS.AUTH}/jwt/register`,
    },
    firebase: {
      login: `${ROOTS.AUTH}/firebase/login`,
      verify: `${ROOTS.AUTH}/firebase/verify`,
      register: `${ROOTS.AUTH}/firebase/register`,
      forgotPassword: `${ROOTS.AUTH}/firebase/forgot-password`,
    },
    auth0: {
      login: `${ROOTS.AUTH}/auth0/login`,
    },
    supabase: {
      login: `${ROOTS.AUTH}/supabase/login`,
      verify: `${ROOTS.AUTH}/supabase/verify`,
      register: `${ROOTS.AUTH}/supabase/register`,
      newPassword: `${ROOTS.AUTH}/supabase/new-password`,
      forgotPassword: `${ROOTS.AUTH}/supabase/forgot-password`,
    },
  },
  authDemo: {
    classic: {
      login: `${ROOTS.AUTH_DEMO}/classic/login`,
      register: `${ROOTS.AUTH_DEMO}/classic/register`,
      forgotPassword: `${ROOTS.AUTH_DEMO}/classic/forgot-password`,
      newPassword: `${ROOTS.AUTH_DEMO}/classic/new-password`,
      verify: `${ROOTS.AUTH_DEMO}/classic/verify`,
    },
    modern: {
      login: `${ROOTS.AUTH_DEMO}/modern/login`,
      register: `${ROOTS.AUTH_DEMO}/modern/register`,
      forgotPassword: `${ROOTS.AUTH_DEMO}/modern/forgot-password`,
      newPassword: `${ROOTS.AUTH_DEMO}/modern/new-password`,
      verify: `${ROOTS.AUTH_DEMO}/modern/verify`,
    },
  },
  // DASHBOARD
  dashboard: {
    root: ROOTS.DASHBOARD,
    mail: `${ROOTS.DASHBOARD}/mail`,
    chat: `${ROOTS.DASHBOARD}/chat`,
    blank: `${ROOTS.DASHBOARD}/blank`,
    kanban: `${ROOTS.DASHBOARD}/kanban`,
    calendar: `${ROOTS.DASHBOARD}/calendar`,
    fileManager: `${ROOTS.DASHBOARD}/file-manager`,
    permission: `${ROOTS.DASHBOARD}/permission`,
    config: `${ROOTS.DASHBOARD}/config`,
    allreports: `${ROOTS.DASHBOARD}/allreports`,
    general: {
      app: `${ROOTS.DASHBOARD}/app`,
      ecommerce: `${ROOTS.DASHBOARD}/ecommerce`,
      analytics: `${ROOTS.DASHBOARD}/analytics`,
      banking: `${ROOTS.DASHBOARD}/banking`,
      booking: `${ROOTS.DASHBOARD}/booking`,
      file: `${ROOTS.DASHBOARD}/file`,
    },
    user: {
      root: `${ROOTS.DASHBOARD}/user`,
      new: `${ROOTS.DASHBOARD}/user/new`,
      list: `${ROOTS.DASHBOARD}/user/list`,
      cards: `${ROOTS.DASHBOARD}/user/cards`,
      profile: `${ROOTS.DASHBOARD}/user/profile`,
      account: `${ROOTS.DASHBOARD}/user/account`,
      edit: (id) => `${ROOTS.DASHBOARD}/user/${id}/edit`,
      demo: {
        edit: `${ROOTS.DASHBOARD}/user/${MOCK_ID}/edit`,
      },
    },
    company: {
      root: `${ROOTS.DASHBOARD}/company`,
      new: `${ROOTS.DASHBOARD}/company/new`,
      list: `${ROOTS.DASHBOARD}/company/list`,
      cards: `${ROOTS.DASHBOARD}/company/cards`,
      profile: `${ROOTS.DASHBOARD}/company/profile`,
      account: `${ROOTS.DASHBOARD}/company/account`,
      edit: (id) => `${ROOTS.DASHBOARD}/company/${id}/edit`,
      demo: {
        edit: `${ROOTS.DASHBOARD}/company/${MOCK_ID}/edit`,
      },
    },
    branch: {
      root: `${ROOTS.DASHBOARD}/branch`,
      new: `${ROOTS.DASHBOARD}/branch/new`,
      list: `${ROOTS.DASHBOARD}/branch/list`,
      cards: `${ROOTS.DASHBOARD}/branch/cards`,
      profile: `${ROOTS.DASHBOARD}/branch/profile`,
      account: `${ROOTS.DASHBOARD}/branch/account`,
      edit: (id) => `${ROOTS.DASHBOARD}/branch/${id}/edit`,
      demo: {
        edit: `${ROOTS.DASHBOARD}/branch/${MOCK_ID}/edit`,
      },
    },
    counter: {
      root: `${ROOTS.DASHBOARD}/counter`,
      new: `${ROOTS.DASHBOARD}/counter/new`,
      list: `${ROOTS.DASHBOARD}/counter/list`,
      cards: `${ROOTS.DASHBOARD}/counter/cards`,
      profile: `${ROOTS.DASHBOARD}/counter/profile`,
      account: `${ROOTS.DASHBOARD}/counter/account`,
      edit: (id) => `${ROOTS.DASHBOARD}/counter/${id}/edit`,
      demo: {
        edit: `${ROOTS.DASHBOARD}/counter/${MOCK_ID}/edit`,
      },
    },
    department: {
      root: `${ROOTS.DASHBOARD}/department`,
      new: `${ROOTS.DASHBOARD}/department/new`,
      list: `${ROOTS.DASHBOARD}/department/list`,
      cards: `${ROOTS.DASHBOARD}/department/cards`,
      profile: `${ROOTS.DASHBOARD}/department/profile`,
      account: `${ROOTS.DASHBOARD}/department/account`,
      edit: (id) => `${ROOTS.DASHBOARD}/department/${id}/edit`,
      demo: {
        edit: `${ROOTS.DASHBOARD}/department/${MOCK_ID}/edit`,
      },
    },
    roles: {
      root: `${ROOTS.DASHBOARD}/roles`,
      new: `${ROOTS.DASHBOARD}/roles/new`,
      list: `${ROOTS.DASHBOARD}/roles/list`,
      cards: `${ROOTS.DASHBOARD}/roles/cards`,
      profile: `${ROOTS.DASHBOARD}/roles/profile`,
      account: `${ROOTS.DASHBOARD}/roles/account`,
      edit: (id) => `${ROOTS.DASHBOARD}/roles/${id}/edit`,
      demo: {
        edit: `${ROOTS.DASHBOARD}/roles/${MOCK_ID}/edit`,
      },
    },
    employee: {
      root: `${ROOTS.DASHBOARD}/employee`,
      new: `${ROOTS.DASHBOARD}/employee/new`,
      list: `${ROOTS.DASHBOARD}/employee/list`,
      cards: `${ROOTS.DASHBOARD}/employee/cards`,
      profile: `${ROOTS.DASHBOARD}/employee/profile`,
      account: `${ROOTS.DASHBOARD}/employee/account`,
      edit: (id) => `${ROOTS.DASHBOARD}/employee/${id}/edit`,
      demo: {
        edit: `${ROOTS.DASHBOARD}/employee/${MOCK_ID}/edit`,
      },
    },
    bankaccount: {
      root: `${ROOTS.DASHBOARD}/bankaccount`,
      new: `${ROOTS.DASHBOARD}/bankaccount/new`,
      list: `${ROOTS.DASHBOARD}/bankaccount/list`,
      cards: `${ROOTS.DASHBOARD}/bankaccount/cards`,
      profile: `${ROOTS.DASHBOARD}/bankaccount/profile`,
      account: `${ROOTS.DASHBOARD}/bankaccount/account`,
      edit: (id) => `${ROOTS.DASHBOARD}/bankaccount/${id}/edit`,
      demo: {
        edit: `${ROOTS.DASHBOARD}/bankaccount/${MOCK_ID}/edit`,
      },
    },
    devices: {
      root: `${ROOTS.DASHBOARD}/devices`,
      new: `${ROOTS.DASHBOARD}/devices/new`,
      list: `${ROOTS.DASHBOARD}/devices/list`,
      cards: `${ROOTS.DASHBOARD}/devices/cards`,
      profile: `${ROOTS.DASHBOARD}/devices/profile`,
      account: `${ROOTS.DASHBOARD}/devices/account`,
      edit: (id) => `${ROOTS.DASHBOARD}/devices/${id}/edit`,
      demo: {
        edit: `${ROOTS.DASHBOARD}/devices/${MOCK_ID}/edit`,
      },
    },
    tax: {
      root: `${ROOTS.DASHBOARD}/tax`,
      new: `${ROOTS.DASHBOARD}/tax/new`,
      list: `${ROOTS.DASHBOARD}/tax/list`,
      cards: `${ROOTS.DASHBOARD}/tax/cards`,
      profile: `${ROOTS.DASHBOARD}/tax/profile`,
      account: `${ROOTS.DASHBOARD}/tax/account`,
      edit: (id) => `${ROOTS.DASHBOARD}/tax/${id}/edit`,
      demo: {
        edit: `${ROOTS.DASHBOARD}/tax/${MOCK_ID}/edit`,
      },
    },
    rateconversion: {
      root: `${ROOTS.DASHBOARD}/rateconversion`,
      new: `${ROOTS.DASHBOARD}/rateconversion/new`,
      list: `${ROOTS.DASHBOARD}/rateconversion/list`,
      cards: `${ROOTS.DASHBOARD}/rateconversion/cards`,
      profile: `${ROOTS.DASHBOARD}/rateconversion/profile`,
      account: `${ROOTS.DASHBOARD}/rateconversion/account`,
      edit: (id) => `${ROOTS.DASHBOARD}/rateconversion/${id}/edit`,
      demo: {
        edit: `${ROOTS.DASHBOARD}/rateconversion/${MOCK_ID}/edit`,
      },
    },
    category: {
      root: `${ROOTS.DASHBOARD}/category`,
      new: `${ROOTS.DASHBOARD}/category/new`,
      list: `${ROOTS.DASHBOARD}/category/list`,
      cards: `${ROOTS.DASHBOARD}/category/cards`,
      profile: `${ROOTS.DASHBOARD}/category/profile`,
      account: `${ROOTS.DASHBOARD}/category/account`,
      edit: (id) => `${ROOTS.DASHBOARD}/category/${id}/edit`,
      demo: {
        edit: `${ROOTS.DASHBOARD}/category/${MOCK_ID}/edit`,
      },
    },
    product: {
      root: `${ROOTS.DASHBOARD}/product`,
      new: `${ROOTS.DASHBOARD}/product/new`,
      list: `${ROOTS.DASHBOARD}/product/list`,
      cards: `${ROOTS.DASHBOARD}/product/cards`,
      profile: `${ROOTS.DASHBOARD}/product/profile`,
      account: `${ROOTS.DASHBOARD}/product/account`,
      edit: (id) => `${ROOTS.DASHBOARD}/product/${id}/edit`,
      demo: {
        edit: `${ROOTS.DASHBOARD}/product/${MOCK_ID}/edit`,
      },
    },
    design: {
      root: `${ROOTS.DASHBOARD}/design`,
      new: `${ROOTS.DASHBOARD}/design/new`,
      list: `${ROOTS.DASHBOARD}/design/list`,
      cards: `${ROOTS.DASHBOARD}/design/cards`,
      profile: `${ROOTS.DASHBOARD}/design/profile`,
      account: `${ROOTS.DASHBOARD}/design/account`,
      edit: (id) => `${ROOTS.DASHBOARD}/design/${id}/edit`,
      demo: {
        edit: `${ROOTS.DASHBOARD}/design/${MOCK_ID}/edit`,
      },
    },
    purity: {
      root: `${ROOTS.DASHBOARD}/purity`,
      new: `${ROOTS.DASHBOARD}/purity/new`,
      list: `${ROOTS.DASHBOARD}/purity/list`,
      cards: `${ROOTS.DASHBOARD}/purity/cards`,
      profile: `${ROOTS.DASHBOARD}/purity/profile`,
      account: `${ROOTS.DASHBOARD}/purity/account`,
      edit: (id) => `${ROOTS.DASHBOARD}/purity/${id}/edit`,
      demo: {
        edit: `${ROOTS.DASHBOARD}/purity/${MOCK_ID}/edit`,
      },
    },
    packet: {
      root: `${ROOTS.DASHBOARD}/packet`,
      new: `${ROOTS.DASHBOARD}/packet/new`,
      list: `${ROOTS.DASHBOARD}/packet/list`,
      cards: `${ROOTS.DASHBOARD}/packet/cards`,
      profile: `${ROOTS.DASHBOARD}/packet/profile`,
      account: `${ROOTS.DASHBOARD}/packet/account`,
      edit: (id) => `${ROOTS.DASHBOARD}/packet/${id}/edit`,
      demo: {
        edit: `${ROOTS.DASHBOARD}/packet/${MOCK_ID}/edit`,
      },
    },
    box: {
      root: `${ROOTS.DASHBOARD}/box`,
      new: `${ROOTS.DASHBOARD}/box/new`,
      list: `${ROOTS.DASHBOARD}/box/list`,
      cards: `${ROOTS.DASHBOARD}/box/cards`,
      profile: `${ROOTS.DASHBOARD}/box/profile`,
      account: `${ROOTS.DASHBOARD}/box/account`,
      edit: (id) => `${ROOTS.DASHBOARD}/box/${id}/edit`,
      demo: {
        edit: `${ROOTS.DASHBOARD}/box/${MOCK_ID}/edit`,
      },
    },
    stone: {
      root: `${ROOTS.DASHBOARD}/stone`,
      new: `${ROOTS.DASHBOARD}/stone/new`,
      list: `${ROOTS.DASHBOARD}/stone/list`,
      cards: `${ROOTS.DASHBOARD}/stone/cards`,
      profile: `${ROOTS.DASHBOARD}/stone/profile`,
      account: `${ROOTS.DASHBOARD}/stone/account`,
      edit: (id) => `${ROOTS.DASHBOARD}/stone/${id}/edit`,
      demo: {
        edit: `${ROOTS.DASHBOARD}/stone/${MOCK_ID}/edit`,
      },
    },
    diamondsizeweightrate: {
      root: `${ROOTS.DASHBOARD}/diamondsizeweightrate`,
      new: `${ROOTS.DASHBOARD}/diamondsizeweightrate/new`,
      list: `${ROOTS.DASHBOARD}/diamondsizeweightrate/list`,
      cards: `${ROOTS.DASHBOARD}/diamondsizeweightrate/cards`,
      profile: `${ROOTS.DASHBOARD}/diamondsizeweightrate/profile`,
      account: `${ROOTS.DASHBOARD}/diamondsizeweightrate/account`,
      edit: (id) => `${ROOTS.DASHBOARD}/diamondsizeweightrate/${id}/edit`,
      demo: {
        edit: `${ROOTS.DASHBOARD}/diamondsizeweightrate/${MOCK_ID}/edit`,
      },
    },
    sku: {
      root: `${ROOTS.DASHBOARD}/sku`,
      new: `${ROOTS.DASHBOARD}/sku/new`,
      list: `${ROOTS.DASHBOARD}/sku/list`,
      cards: `${ROOTS.DASHBOARD}/sku/cards`,
      profile: `${ROOTS.DASHBOARD}/sku/profile`,
      account: `${ROOTS.DASHBOARD}/sku/account`,
      edit: (id) => `${ROOTS.DASHBOARD}/sku/${id}/edit`,
      demo: {
        edit: `${ROOTS.DASHBOARD}/sku/${MOCK_ID}/edit`,
      },
    },
    rates: {
      root: `${ROOTS.DASHBOARD}/rates`,
      new: `${ROOTS.DASHBOARD}/rates/new`,
      list: `${ROOTS.DASHBOARD}/rates/list`,
      cards: `${ROOTS.DASHBOARD}/rates/cards`,
      profile: `${ROOTS.DASHBOARD}/rates/profile`,
      account: `${ROOTS.DASHBOARD}/rates/account`,
      edit: (id) => `${ROOTS.DASHBOARD}/rates/${id}/edit`,
      demo: {
        edit: `${ROOTS.DASHBOARD}/rates/${MOCK_ID}/edit`,
      },
    },
    collection: {
      root: `${ROOTS.DASHBOARD}/collection`,
      new: `${ROOTS.DASHBOARD}/collection/new`,
      list: `${ROOTS.DASHBOARD}/collection/list`,
      cards: `${ROOTS.DASHBOARD}/collection/cards`,
      profile: `${ROOTS.DASHBOARD}/collection/profile`,
      account: `${ROOTS.DASHBOARD}/collection/account`,
      edit: (id) => `${ROOTS.DASHBOARD}/collection/${id}/edit`,
      demo: {
        edit: `${ROOTS.DASHBOARD}/collection/${MOCK_ID}/edit`,
      },
    },
    occasion: {
      root: `${ROOTS.DASHBOARD}/occasion`,
      new: `${ROOTS.DASHBOARD}/occasion/new`,
      list: `${ROOTS.DASHBOARD}/occasion/list`,
      cards: `${ROOTS.DASHBOARD}/occasion/cards`,
      profile: `${ROOTS.DASHBOARD}/occasion/profile`,
      account: `${ROOTS.DASHBOARD}/occasion/account`,
      edit: (id) => `${ROOTS.DASHBOARD}/occasion/${id}/edit`,
      demo: {
        edit: `${ROOTS.DASHBOARD}/occasion/${MOCK_ID}/edit`,
      },
    },
    purchaseentry: {
      root: `${ROOTS.DASHBOARD}/purchaseentry`,
      new: `${ROOTS.DASHBOARD}/purchaseentry/new`,
      list: `${ROOTS.DASHBOARD}/purchaseentry/list`,
      cards: `${ROOTS.DASHBOARD}/purchaseentry/cards`,
      profile: `${ROOTS.DASHBOARD}/purchaseentry/profile`,
      account: `${ROOTS.DASHBOARD}/purchaseentry/account`,
      edit: (id) => `${ROOTS.DASHBOARD}/purchaseentry/${id}/edit`,
      demo: {
        edit: `${ROOTS.DASHBOARD}/purchaseentry/${MOCK_ID}/edit`,
      },
    },
    createpacket: {
      root: `${ROOTS.DASHBOARD}/createpacket`,
      new: `${ROOTS.DASHBOARD}/createpacket/new`,
      list: `${ROOTS.DASHBOARD}/createpacket/list`,
      cards: `${ROOTS.DASHBOARD}/createpacket/cards`,
      profile: `${ROOTS.DASHBOARD}/createpacket/profile`,
      account: `${ROOTS.DASHBOARD}/createpacket/account`,
      edit: (id) => `${ROOTS.DASHBOARD}/createpacket/${id}/edit`,
      demo: {
        edit: `${ROOTS.DASHBOARD}/createpacket/${MOCK_ID}/edit`,
      },
    },
    addbulkstocknew: {
      root: `${ROOTS.DASHBOARD}/addbulkstocknew`,
      new: `${ROOTS.DASHBOARD}/addbulkstocknew/new`,
      list: `${ROOTS.DASHBOARD}/addbulkstocknew/list`,
      cards: `${ROOTS.DASHBOARD}/addbulkstocknew/cards`,
      profile: `${ROOTS.DASHBOARD}/addbulkstocknew/profile`,
      account: `${ROOTS.DASHBOARD}/addbulkstocknew/account`,
      edit: (id) => `${ROOTS.DASHBOARD}/addbulkstocknew/${id}/edit`,
      demo: {
        edit: `${ROOTS.DASHBOARD}/addbulkstocknew/${MOCK_ID}/edit`,
      },
    },
    addsinglestock: {
      root: `${ROOTS.DASHBOARD}/addsinglestock`,
      new: `${ROOTS.DASHBOARD}/addsinglestock/new`,
      list: `${ROOTS.DASHBOARD}/addsinglestock/list`,
      cards: `${ROOTS.DASHBOARD}/addsinglestock/cards`,
      profile: `${ROOTS.DASHBOARD}/addsinglestock/profile`,
      account: `${ROOTS.DASHBOARD}/addsinglestock/account`,
      edit: (id) => `${ROOTS.DASHBOARD}/addsinglestock/${id}/edit`,
      demo: {
        edit: `${ROOTS.DASHBOARD}/addsinglestock/${MOCK_ID}/edit`,
      },
    },
    invoice: {
      root: `${ROOTS.DASHBOARD}/invoice`,
      new: `${ROOTS.DASHBOARD}/invoice/new`,
      list: `${ROOTS.DASHBOARD}/invoice/list`,
      cards: `${ROOTS.DASHBOARD}/invoice/cards`,
      profile: `${ROOTS.DASHBOARD}/invoice/profile`,
      account: `${ROOTS.DASHBOARD}/invoice/account`,
      edit: (id) => `${ROOTS.DASHBOARD}/invoice/${id}/edit`,
      demo: {
        edit: `${ROOTS.DASHBOARD}/invoice/${MOCK_ID}/edit`,
      },
    },
    makepayments: {
      root: `${ROOTS.DASHBOARD}/makepayments`,
      new: `${ROOTS.DASHBOARD}/makepayments/new`,
      list: `${ROOTS.DASHBOARD}/makepayments/list`,
      cards: `${ROOTS.DASHBOARD}/makepayments/cards`,
      profile: `${ROOTS.DASHBOARD}/makepayments/profile`,
      account: `${ROOTS.DASHBOARD}/makepayments/account`,
      edit: (id) => `${ROOTS.DASHBOARD}/makepayments/${id}/edit`,
      demo: {
        edit: `${ROOTS.DASHBOARD}/makepayments/${MOCK_ID}/edit`,
      },
    },
    receivepayments: {
      root: `${ROOTS.DASHBOARD}/receivepayments`,
      new: `${ROOTS.DASHBOARD}/receivepayments/new`,
      list: `${ROOTS.DASHBOARD}/receivepayments/list`,
      cards: `${ROOTS.DASHBOARD}/receivepayments/cards`,
      profile: `${ROOTS.DASHBOARD}/receivepayments/profile`,
      account: `${ROOTS.DASHBOARD}/receivepayments/account`,
      edit: (id) => `${ROOTS.DASHBOARD}/receivepayments/${id}/edit`,
      demo: {
        edit: `${ROOTS.DASHBOARD}/receivepayments/${MOCK_ID}/edit`,
      },
    },
    creditnotesalereturn: {
      root: `${ROOTS.DASHBOARD}/creditnotesalereturn`,
      new: `${ROOTS.DASHBOARD}/creditnotesalereturn/new`,
      list: `${ROOTS.DASHBOARD}/creditnotesalereturn/list`,
      cards: `${ROOTS.DASHBOARD}/creditnotesalereturn/cards`,
      profile: `${ROOTS.DASHBOARD}/creditnotesalereturn/profile`,
      account: `${ROOTS.DASHBOARD}/creditnotesalereturn/account`,
      edit: (id) => `${ROOTS.DASHBOARD}/creditnotesalereturn/${id}/edit`,
      demo: {
        edit: `${ROOTS.DASHBOARD}/creditnotesalereturn/${MOCK_ID}/edit`,
      },
    },
    debitnotesalereturn: {
      root: `${ROOTS.DASHBOARD}/debitnotesalereturn`,
      new: `${ROOTS.DASHBOARD}/debitnotesalereturn/new`,
      list: `${ROOTS.DASHBOARD}/debitnotesalereturn/list`,
      cards: `${ROOTS.DASHBOARD}/debitnotesalereturn/cards`,
      profile: `${ROOTS.DASHBOARD}/debitnotesalereturn/profile`,
      account: `${ROOTS.DASHBOARD}/debitnotesalereturn/account`,
      edit: (id) => `${ROOTS.DASHBOARD}/debitnotesalereturn/${id}/edit`,
      demo: {
        edit: `${ROOTS.DASHBOARD}/debitnotesalereturn/${MOCK_ID}/edit`,
      },
    },
    stocktransfer: {
      root: `${ROOTS.DASHBOARD}/stocktransfer`,
      new: `${ROOTS.DASHBOARD}/stocktransfer/new`,
      list: `${ROOTS.DASHBOARD}/stocktransfer/list`,
      cards: `${ROOTS.DASHBOARD}/stocktransfer/cards`,
      profile: `${ROOTS.DASHBOARD}/stocktransfer/profile`,
      account: `${ROOTS.DASHBOARD}/stocktransfer/account`,
      edit: (id) => `${ROOTS.DASHBOARD}/stocktransfer/${id}/edit`,
      demo: {
        edit: `${ROOTS.DASHBOARD}/stocktransfer/${MOCK_ID}/edit`,
      },
    },
    vendortounche: {
      root: `${ROOTS.DASHBOARD}/vendortounche`,
      new: `${ROOTS.DASHBOARD}/vendortounche/new`,
      list: `${ROOTS.DASHBOARD}/vendortounche/list`,
      cards: `${ROOTS.DASHBOARD}/vendortounche/cards`,
      profile: `${ROOTS.DASHBOARD}/vendortounche/profile`,
      account: `${ROOTS.DASHBOARD}/vendortounche/account`,
      edit: (id) => `${ROOTS.DASHBOARD}/vendortounche/${id}/edit`,
      demo: {
        edit: `${ROOTS.DASHBOARD}/vendortounche/${MOCK_ID}/edit`,
      },
    },
    customertounche: {
      root: `${ROOTS.DASHBOARD}/customertounche`,
      new: `${ROOTS.DASHBOARD}/customertounche/new`,
      list: `${ROOTS.DASHBOARD}/customertounche/list`,
      cards: `${ROOTS.DASHBOARD}/customertounche/cards`,
      profile: `${ROOTS.DASHBOARD}/customertounche/profile`,
      account: `${ROOTS.DASHBOARD}/customertounche/account`,
      edit: (id) => `${ROOTS.DASHBOARD}/customertounche/${id}/edit`,
      demo: {
        edit: `${ROOTS.DASHBOARD}/customertounche/${MOCK_ID}/edit`,
      },
    },
  },
};
